# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da46eea698391e0d82b187710c5c47f8a1fcd74e0961b4e72ec4b2dcd2f12130f9ad3c12b98369801fb7bdca0cbb6aa4e5c2bc2e72aded1614a794ad4648fdd8

test:
  secret_key_base: 4dd69260df64070892262897b0bda4c21e11ba766048dd07556efa266376d2b4fba87742c582ce26b21623159b8a78133522462d1af9991a306c7a04c1d55ff0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
